// backend/models/Revenue.js
import mongoose from "mongoose";

const revenueSchema = new mongoose.Schema(
  {
    // 👤 Person who generated revenue (Intern / Employee / Manager)
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },

    // 👔 Manager who added this revenue (null if admin/self)
    manager: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null,
      index: true,
    },

    // 💰 Revenue amount generated by company
    amount: {
      type: Number,
      required: true,
      min: 0,
    },

    // 📅 Revenue date (normalized to start of day)
    date: {
      type: Date,
      required: true,
      index: true,
    },

    // 📝 Optional note by manager/admin
    description: {
      type: String,
      default: "",
      trim: true,
    },
  },
  {
    timestamps: true,
  }
);

/**
 * 🔒 RULE:
 * One user can have ONLY ONE revenue entry per day
 */
revenueSchema.index({ user: 1, date: 1 }, { unique: true });

export default mongoose.model("Revenue", revenueSchema);
